<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
    
<!DOCTYPE HTML>
<!--
	Minimaxing by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Two Column 1 - Minimaxing by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="/assets/css/main.css" />
	</head>
	<body>
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<jsp:include page="/header-menu.jsp">
									<jsp:param name="menu" value="study" />
								</jsp:include>

							</div>
						</div>
					</div>
				</div>

			<!-- Main -->
				<div id="main">
					<div class="container">
						<div class="row main-row">
							<div class="col-8 col-12-medium">

								<section>
									<h2>오라클 설치하기</h2>
									<p>
										https://www.oracle.com/kr 에 접속 개발자 > 리소스 다운로드 > 데이터베이스 > Database Express Edition<br/>
										https://www.oracle.com/kr/database/technologies/xe-downloads.html에 접속한다.<br/>
										Oracle Database 21c Express Edition for Windows x64, OracleXE213_Win64.zip를 다운로드 및 압축 해제 후 설치<br/>
										setup.exe 관리자권한으로 설치<br/>
										Oracle Database Express Edition 접속 정보: <br/>
										다중 테넌트 컨테이너 데이터베이스 : localhost:1521<br/>
										플러그인할 수 있는 데이터베이스 : localhost:1521/XEPDB1<br/>
										EM Express URL : https://localhost:5500/em<br/>
									</p>
									
									<h2>SQL Developer 설치</h2>
									<p>개발자 > Developer Resource Center > 리소스 > 다운로드 > 개발자도구 > SQL Developer > Windows 32-bit/64-bit 파일 다운로드
									
									<h2>서비스네임 확인</h2>
									<pre>
# tnsnames.ora Network Configuration File: C:\app\KBS\product\21c\homes\OraDB21Home1\NETWORK\ADMIN\tnsnames.ora
# Generated by Oracle configuration tools.

XE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.10.101)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )

LISTENER_XE =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.10.101)(PORT = 1521))


ORACLR_CONNECTION_DATA =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
    (CONNECT_DATA =
      (SID = CLRExtProc)
      (PRESENTATION = RO)
    )
  )
									</pre>									
									
									<pre>
C:\Users\KBS>tnsping XE

TNS Ping Utility for 64-bit Windows: Version 21.0.0.0.0 - Production on 31-1월 -2025 11:23:09

Copyright (c) 1997, 2021, Oracle.  All rights reserved.

사용된 매개변수 파일:
C:\app\KBS\product\21c\homes\OraDB21Home1\network\admin\sqlnet.ora


별칭 분석을 위해 TNSNAMES 어댑터 사용
(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.10.101)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = XE)))에 접속하려고 시도하는 중
확인(0밀리초)									
									</pre>
									
									<h2>리스너</h2>
									<p>lsnrctl status, stop, start</p>
									
									<h2>DBeaver 접속하기</h2>
									<img src="/study/oracle/img/2025-02-01 135627.png" />
									<br/><br/>
									<img src="/study/oracle/img/2025-01-31 124432.png" />
									<p>SELECT con_id, name, open_mode FROM v$containers; 정상적으로 XEPDB1이라는 PDB에 접속되었음</p>
				
									<h2>오라클 샘플 데이터 설치</h2>
									<p>https://github.com/oracle-samples/db-sample-schemas/releases/tag/v23.3 접속<br/>
									db-sample-schemas-23.3.zip파일 다운로드 human_resources폴더로 이동 hr_create.sql로 테이블 생성 hr_populate.sql파일로 데이터 생성</p>
								</section>

							</div>
							<div class="col-4 col-12-medium">

								<jsp:include page="/study/oracle/right.jsp"></jsp:include>
								
							</div>
						</div>
					</div>
				</div>

			<!-- Footer -->
				<div id="footer-wrapper">
					<div class="container">
						<div class="row">
							<div class="col-8 col-12-medium">

								<section>
									<h2>How about a truckload of links?</h2>
									<div>
										<div class="row">
											<div class="col-3 col-6-medium col-12-small">
												<ul class="link-list">
													<li><a href="#">Sed neque nisi consequat</a></li>
													<li><a href="#">Dapibus sed mattis blandit</a></li>
													<li><a href="#">Quis accumsan lorem</a></li>
													<li><a href="#">Suspendisse varius ipsum</a></li>
													<li><a href="#">Eget et amet consequat</a></li>
												</ul>
											</div>
											<div class="col-3 col-6-medium col-12-small">
												<ul class="link-list">
													<li><a href="#">Quis accumsan lorem</a></li>
													<li><a href="#">Sed neque nisi consequat</a></li>
													<li><a href="#">Eget et amet consequat</a></li>
													<li><a href="#">Dapibus sed mattis blandit</a></li>
													<li><a href="#">Vitae magna sed dolore</a></li>
												</ul>
											</div>
											<div class="col-3 col-6-medium col-12-small">
												<ul class="link-list">
													<li><a href="#">Sed neque nisi consequat</a></li>
													<li><a href="#">Dapibus sed mattis blandit</a></li>
													<li><a href="#">Quis accumsan lorem</a></li>
													<li><a href="#">Suspendisse varius ipsum</a></li>
													<li><a href="#">Eget et amet consequat</a></li>
												</ul>
											</div>
											<div class="col-3 col-6-medium col-12-small">
												<ul class="link-list">
													<li><a href="#">Quis accumsan lorem</a></li>
													<li><a href="#">Sed neque nisi consequat</a></li>
													<li><a href="#">Eget et amet consequat</a></li>
													<li><a href="#">Dapibus sed mattis blandit</a></li>
													<li><a href="#">Vitae magna sed dolore</a></li>
												</ul>
											</div>
										</div>
									</div>
								</section>

							</div>
							<div class="col-4 col-12-medium">

								<section>
									<h2>Something of interest</h2>
									<p>Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed.
									Suspendisse eu varius nibh. Suspendisse vitae magna eget odio amet
									mollis justo facilisis quis. Sed sagittis mauris amet tellus gravida
									lorem ipsum dolor sit blandit.</p>
									<footer class="controls">
										<a href="#" class="button">Oh, please continue ....</a>
									</footer>
								</section>

							</div>
						</div>
						<div class="row">
							<div class="col-12">

								<div id="copyright">
									&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
								</div>

							</div>
						</div>
					</div>
				</div>

		</div>

		<!-- Scripts -->
			<script src="/assets/js/jquery.min.js"></script>
			<script src="/assets/js/browser.min.js"></script>
			<script src="/assets/js/breakpoints.min.js"></script>
			<script src="/assets/js/util.js"></script>
			<script src="/assets/js/main.js"></script>

	</body>
</html>